### ISSUE TITLE
do not perform lookups unless opted in

### ISSUE THREAD

**Issue by zzmp** [metaphor-xyz/davatar-helpers#18]
The passed provider may provide a way to do ENS lookups, but if it does not, no lookups should be performed unless the integrator opts in. This prevents data/privacy leaking.

**Comment by zzmp** [comment]
@davatar/react makes calls to alchemy for ENS resolution on chainIDs besides 1, 3, 4, 5 ([code](https://github.com/metaphor-xyz/davatar-helpers/blob/f9bec8be86cc4433f6c8f5036b67c58bf5ae360e/packages/react/src/index.tsx#L46)).

**Comment by carlosdp** [comment]
I'm not sure I understand, what's the leak vector here? This library looks up ENS on mainnet (unless on a testnet with ENS deployed, where we assume we want to test with an ENS on that chain), which should be the correct behavior, even if the "connected" chain is a different one (say Polygon).
