### ISSUE TITLE
Overloading etherscan with API calls / caching not working

### ISSUE THREAD

**Issue by davidthomasparks** [metaphor-xyz/davatar-helpers#21]
Hi there,

This package has become a huge bottleneck in our app due to the repeated lookups for an address. I don't believe the caching is actually working in the latest version of this package? Every render of a Davatar it fires off hundreds if not thousands of requests to getUrl.js. Any insights?

<img width="1058" alt="Screen Shot 2022-03-17 at 11 00 24 AM" src="https://user-images.githubusercontent.com/97011546/158866444-fca441ba-ffa7-4a0c-9134-13e517d14f65.png">

**Comment by carlosdp** [comment]
I'll take a look at this, for some reason I haven't been receiving notifications from github so just saw this!

**Comment by carlosdp** [comment]
What version is this on?
