### ISSUE TITLE
Good Project! I extract the core logic and removed React.

### ISSUE THREAD

**Issue by taurenshaman** [metaphor-xyz/davatar-helpers#22]
Thanks for your work!
I met it from the tourial [create a web3 forum with polygon](https://www.pointer.gg/tutorials/create-a-web3-forum-with-polygon/1cb8f005-08f4-48a2-9d82-cd963e16f7f1). 
The davatar is very good and easy to use.
But I usually worked on Vue. So I extract the core logic and removed React: https://github.com/rune-box/avatar-core

![image](https://user-images.githubusercontent.com/1308706/159474900-ffaddf62-bb89-4899-bb09-eacb79e4621e.png)

Next, I will research on the logic of `Blockies` and `Jazzicon`.

Thank you again!
❤❤❤❤❤❤❤

**Comment by carlosdp** [comment]
Nice! 👍 If you want to contribute back a Vue package, it's been on the list! Also breaking out the core into a separate package is too. I just haven't had a ton of time to work on this in a while.
