### ISSUE TITLE
Default Component Always Shown if Address is a State

### ISSUE THREAD

**Issue by e6654321** [metaphor-xyz/davatar-helpers#23]
Adding a `defaultComponent` and having the value for `address` as a state will result in `defaultComponent` to always be rendered. My `address` is undefined at first and it gets populated for the string value after the web3 hook is done logging in.

**Comment by carlosdp** [comment]
Hmm are you sure the address in question has an avatar defined? If it does not, the defaultComponent will remain showing, it will not be replaced by a Blockie or Jazzicon (the idea behind defaultComponent is for providing a custom implementation of "no avatar set" state)
