### ISSUE TITLE
could you add Explanation of provider and graphApiKey in RM

### ISSUE THREAD

**Issue by aboutmydreams** [metaphor-xyz/davatar-helpers#24]
provider = { provider } 
graphApiKey = { apiKey } 

As a new person to web3, I don't understand the purpose of these two parameters, and how to get the key, can you help me? Thanks!

**Comment by carlosdp** [comment]
`graphApiKey` is deprecated, so don't worry about that. A `provider` is an Ethers.JS or Web3.js RPC provider!
