### ISSUE TITLE
Infinite state update in v1.10.0

### ISSUE THREAD

**Issue by jac0x** [metaphor-xyz/davatar-helpers#26]
When using @davatar/react@1.10.0, the app enters infinite state update while connecting the account.

**Comment by carlosdp** [comment]
Does this exist on the latest version, 1.10.3, as well? Also, could you provide a code snippet by any chance?

**Comment by carlosdp** [comment]
Fixed in #27, thanks!

**Comment by jac0x** [comment]
Thanks a lot!
