### ISSUE TITLE
Please support `data` field

### ISSUE THREAD

**Issue by makoto** [metaphor-xyz/davatar-helpers#3]
As in the spec https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182#data

**Comment by carlosdp** [comment]
Discussed offline, but the library does already support the `data` URL type. The library lets anything that doesn't match another protocol into the `img` tag directly, which the `data` URL falls under.

This allows easy support of any and all types that are directly parseable by the HTML img tag, without explicit support needed. If the URI is just invalid, the avatar never switches from the generated Jazzicon 😄
